import './globals.css'
import { Orbitron, Roboto_Flex } from 'next/font/google'

const orbitron = Orbitron({ subsets: ['latin'], variable: '--font-orbitron' })
const roboto = Roboto_Flex({ subsets: ['latin'], variable: '--font-roboto' })
export const metadata = {
  title: 'Coaching Esportivo',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={`${roboto.variable} ${orbitron.variable} font-roboto`}>{children}</body>
    </html>
  )
}
